Vagrant.configure("2") do |config|

  config.vm.define :{{project_name}}_vm do |{{project_name}}_config|
    # Every Vagrant virtual environment requires a box to build off of.
    {{project_name}}_config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
    {{project_name}}_config.vm.hostname = "{{project_name}}.placeholder.com"

    # Forward a port from the guest to the host, which allows for outside
    # computers to access the VM, whereas host only networking does not.
    {{project_name}}_config.vm.network :forwarded_port, host: 9171, guest: 8001	

    {{project_name}}_config.vm.synced_folder "../", "/vagrant", id: "1",
          mount_options: ["dmode=775", "fmode=764"]
  
    {{project_name}}_config.vm.provision :shell do |shell|
      shell.path = "shell/main.sh"
    end

    {{project_name}}_config.vm.provision :puppet do |puppet|
      puppet.manifests_path = 'puppet/manifests'
      puppet.manifest_file  = "default.pp"
      puppet.module_path    = ['puppet/modules', 'puppet/modules-contrib']
    end

  end
end

